### ISSUE TITLE
Player count from precedent map stays when the new map you check don't have one

### ISSUE THREAD

**Issue by Banalian** [openplanet-nl/tmio#63] opened 2023-07-31 23:12 UTC
Hi!

I was looking into an error I had on some personnal project, and wanted to check a map on tm.io.

To do that, I went to a random map (for example, today's TOTD with 8k people), then changed the url to use the map ID I had. When I did this, I ended up on the map, which has no leaderboard, but the playercount was the same as the TOTD. After a refresh, it went back to normal, but I am able to consistently reproduce it. I'll attach some screenshot (I am censoring some information as the map isn't public)

TOTD  : 
![image](https://github.com/openplanet-nl/tmio/assets/64379456/8621cc0b-baa3-4dc4-9a5e-dea8ee88cad1)

New map :
![image](https://github.com/openplanet-nl/tmio/assets/64379456/364558e3-a519-4079-97fc-d00761bdf1cb)

After Refresh : 
![image](https://github.com/openplanet-nl/tmio/assets/64379456/656726aa-6265-4100-824a-f8242df1df59)

**Comment by davidbmaier** [comment] 2023-08-01 09:23
Are you doing this on a map's leaderboard in the context of a campaign (i.e. `https://trackmania.io/#/campaigns/leaderboard/:groupId/:mapUid`)?
I can reproduce it there, but the new page is pointless anyway - there is no leaderboard for that map using the previous map's `groupId`. If I copy the correct `groupId` as well, the player count updates correctly.

If I use `https://trackmania.io/#/leaderboard/:mapUid` and change the map's ID there, everything works fine on my end.

I'd agree it's a little confusing, but you're basically visiting a page that doesn't make any sense anyway.
I'll take a quick look at the logic to see if there's an easy way to fix this behavior. But I'd say this is just an unintended way to use the site.

**Comment by davidbmaier** [comment] 2023-08-01 09:31
Found the issue, looks like the leaderboard logic exited early when there are no records at all, so it didn't set the player count correctly.
This would only happen on invalid `groupId`/`mapUid` combinations or on maps that simply have no records at all - so I guess it's still a valid finding for those cases.
Should get fixed on the next website deployment.

**Closed as completed by davidbmaier** 2023-08-01 09:31 UTC
