### ISSUE TITLE
https://trackmania.io/#/rooms Use of Kansas / https://trackmania.io/#/clubs minse Capital as otherwise

### ISSUE THREAD

**Issue by w1lla** [openplanet-nl/tmio#79] opened 2024-01-26 22:24 UTC
Weird bug.

But in rooms try to type Kansas or Venlo or in clubs minse and it will say load more

**Comment by davidbmaier** [comment] 2024-01-26 22:33
For reference, the problem is likely that the site doesn't check what the total number of items is, and it always displays a "Load more" button at the end of the last retrieved page.
We should instead properly check whether the latest page is the last one and remove the button.

This applies to a couple similar panels, probably worth going through the main ones (that can be searched).

**Comment by davidbmaier** [comment] 2024-01-28 11:51
Should be fixed for Clubs, Rooms and Campaigns. If you notice the same problem on other pages, feel free to reopen this issue.

**Closed as completed by davidbmaier** 2024-01-28 11:51 UTC
